'use client'

import { useEffect, useState } from 'react'
import { Beaker, Pause, Play, Plus, RefreshCw, ShieldCheck } from 'lucide-react'

type Org={id:string;name:string}; type Property={id:string;organization_id:string;name:string}; type Template={id:string;organization_id:string;name:string;description:string;version:number};
 type Automation={id:string;organization_id:string;property_id:string;name:string;status:string;config:Record<string,unknown>;deployed_version:number|null;last_run_at:string|null;last_error?:string|null;automation_templates:{name:string;description:string;version:number}|null;properties:{name:string}|null}

export function AutomationCenter(){
 const [data,setData]=useState<{organizations:Org[];properties:Property[];templates:Template[];automations:Automation[]}>({organizations:[],properties:[],templates:[],automations:[]}); const [org,setOrg]=useState(''); const [property,setProperty]=useState(''); const [template,setTemplate]=useState(''); const [message,setMessage]=useState<string|null>(null); const [busy,setBusy]=useState(false)
 async function load(){const response=await fetch('/api/admin/automations',{cache:'no-store'});const result=await response.json().catch(()=>null);if(!response.ok||!result?.success)throw new Error(result?.error||'No fue posible cargar las reglas.');setData(result.data);if(!org&&result.data.organizations[0])setOrg(result.data.organizations[0].id)}
 useEffect(()=>{load().catch((error)=>setMessage(error.message))},[])
 async function command(body:Record<string,unknown>){setBusy(true);setMessage(null);try{const response=await fetch('/api/admin/automations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await response.json().catch(()=>null);if(!response.ok||!result?.success)throw new Error(result?.error||'No fue posible completar la acción.');setMessage(result.message);await load()}catch(error){setMessage(error instanceof Error?error.message:'No fue posible completar la acción.')}finally{setBusy(false)}}
 const properties=data.properties.filter((item)=>item.organization_id===org),templates=data.templates.filter((item)=>item.organization_id===org)
 return <div className="space-y-6"><header className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-sm uppercase tracking-[0.2em] text-[#9DD2F2]">Respuesta automática</p><h1 className="mt-2 text-3xl font-light text-white">Automatizaciones</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-white/55">Prepara reglas por sitio, simula su efecto y activa sólo cuando la instalación esté conectada.</p></div><button onClick={()=>load()} className="btn-secondary inline-flex items-center gap-2 px-4 py-2 text-sm"><RefreshCw className="h-4 w-4"/> Actualizar</button></header>{message&&<p className="rounded-xl border border-white/10 bg-white/5 p-3 text-sm text-white/70">{message}</p>}
 <section className="glass-card p-6"><div className="grid gap-4 lg:grid-cols-4"><select aria-label="Empresa" value={org} onChange={(e)=>{setOrg(e.target.value);setProperty('');setTemplate('')}} className="rounded-xl bg-[#123A5A] px-4 py-3 text-sm text-white"><option value="">Empresa...</option>{data.organizations.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select><select aria-label="Sitio" value={property} onChange={(e)=>setProperty(e.target.value)} className="rounded-xl bg-[#123A5A] px-4 py-3 text-sm text-white"><option value="">Sitio...</option>{properties.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select><select aria-label="Plantilla de automatización" value={template} onChange={(e)=>setTemplate(e.target.value)} className="rounded-xl bg-[#123A5A] px-4 py-3 text-sm text-white"><option value="">Plantilla...</option>{templates.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select><button disabled={busy||!property||!template} onClick={()=>{const selected=templates.find((item)=>item.id===template);command({action:'create',propertyId:property,templateId:template,name:selected?.name||'Regla de seguridad',config:{}})}} className="btn-primary inline-flex items-center justify-center gap-2 px-4 py-3 text-sm disabled:opacity-50"><Plus className="h-4 w-4"/> Crear regla</button></div>{org&&templates.length===0&&<button disabled={busy} onClick={()=>command({action:'seed',organizationId:org})} className="mt-4 inline-flex items-center gap-2 text-sm text-[#9DD2F2]"><ShieldCheck className="h-4 w-4"/> Preparar biblioteca recomendada</button>}</section>
 <section className="grid gap-4 xl:grid-cols-2">{data.automations.length===0?<div className="glass-card col-span-full p-10 text-center text-sm text-white/45">Aún no hay reglas configuradas.</div>:data.automations.map((rule)=><article key={rule.id} className="glass-card p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-[0.16em] text-white/40">{rule.properties?.name||'Sitio'}</p><h2 className="mt-2 text-xl font-light text-white">{rule.name}</h2><p className="mt-2 text-sm leading-6 text-white/55">{rule.automation_templates?.description}</p></div><span className={`rounded-full px-3 py-1 text-xs ${rule.status==='active'?'bg-emerald-500/15 text-emerald-200':rule.status==='error'?'bg-red-500/15 text-red-200':'bg-white/8 text-white/55'}`}>{rule.status==='active'?'Activa':rule.status==='paused'?'Pausada':rule.status==='ready'?'Esperando confirmación':rule.status==='error'?'Con error':'Borrador'}</span></div>{rule.last_error&&<p className="mt-4 rounded-xl border border-red-400/20 bg-red-500/10 p-3 text-sm text-red-100">{rule.last_error}</p>}<div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-xl bg-white/5 p-3"><p className="text-xs text-white/35">Versión</p><p className="mt-1 text-sm text-white">{rule.deployed_version||rule.automation_templates?.version||1}</p></div><div className="rounded-xl bg-white/5 p-3"><p className="text-xs text-white/35">Última prueba</p><p className="mt-1 text-sm text-white">{rule.last_run_at?new Intl.DateTimeFormat('es-CL',{dateStyle:'short',timeStyle:'short'}).format(new Date(rule.last_run_at)):'Sin prueba'}</p></div></div><div className="mt-5 flex flex-wrap gap-2"><button disabled={busy} onClick={()=>command({action:'simulate',automationId:rule.id})} className="btn-secondary inline-flex items-center gap-2 px-4 py-2 text-sm"><Beaker className="h-4 w-4"/> Simular</button>{rule.status==='active'?<button disabled={busy} onClick={()=>command({action:'deploy',automationId:rule.id,desiredStatus:'paused'})} className="btn-secondary inline-flex items-center gap-2 px-4 py-2 text-sm"><Pause className="h-4 w-4"/> Enviar pausa</button>:rule.status!=='ready'&&<button disabled={busy} onClick={()=>command({action:'deploy',automationId:rule.id,desiredStatus:'active'})} className="btn-primary inline-flex items-center gap-2 px-4 py-2 text-sm"><Play className="h-4 w-4"/> Enviar al sitio</button>}</div></article>)}</section></div>
}
