export const securityAutomationLibrary = [
  { template_key: 'motion_after_hours', name: 'Movimiento fuera de horario', description: 'Eleva una señal de movimiento cuando el sitio debería estar sin actividad.', trigger_kind: 'motion', version: 1, default_config: { schedule: { from: '22:00', to: '06:00' }, severity: 'critical', capture: true } },
  { template_key: 'entry_open_too_long', name: 'Acceso abierto demasiado tiempo', description: 'Avisa cuando una puerta o portón permanece abierto sobre el límite definido.', trigger_kind: 'entry_open', version: 1, default_config: { openSeconds: 180, severity: 'warning', escalationMinutes: 5 } },
  { template_key: 'smoke_or_gas', name: 'Humo o gas detectado', description: 'Genera respuesta crítica inmediata y solicita activación de la respuesta local.', trigger_kind: 'smoke_gas', version: 1, default_config: { severity: 'critical', localSiren: true, immediate: true } },
  { template_key: 'water_leak', name: 'Fuga de agua', description: 'Crea una alerta y permite solicitar cierre local de válvula cuando esté disponible.', trigger_kind: 'water', version: 1, default_config: { severity: 'critical', closeValve: false } },
  { template_key: 'device_offline', name: 'Equipo sin comunicación', description: 'Abre seguimiento técnico cuando un equipo crítico deja de reportar.', trigger_kind: 'device_offline', version: 1, default_config: { offlineMinutes: 10, severity: 'warning' } },
  { template_key: 'battery_low', name: 'Batería preventiva', description: 'Agrupa equipos con batería baja antes de que queden fuera de servicio.', trigger_kind: 'battery_low', version: 1, default_config: { threshold: 20, severity: 'warning' } },
  { template_key: 'unexpected_disarm', name: 'Desarme fuera de horario', description: 'Solicita validación del responsable cuando el sistema cambia a desarmado fuera de horario.', trigger_kind: 'disarm', version: 1, default_config: { schedule: { from: '21:00', to: '07:00' }, severity: 'critical' } },
  { template_key: 'multiple_signals', name: 'Múltiples señales en una zona', description: 'Eleva severidad cuando varias señales coinciden en la misma zona y ventana de tiempo.', trigger_kind: 'multi_signal', version: 1, default_config: { windowSeconds: 90, minimumSignals: 2, severity: 'critical' } },
] as const
