import type { Locale } from '@/lib/locales'

export const marketing = {
  es: {
    nav: {
      solutions: 'Soluciones',
      portal: 'Portal',
      contact: 'Contacto',
      language: 'EN',
    },
    footer: {
      description: 'SegurIA conecta tu operación para que veas qué está pasando, entiendas qué requiere atención y puedas actuar mejor.',
      solutions: 'Soluciones',
      seeSolution: 'Ver solución',
      clientPortal: 'Portal cliente',
      company: 'Empresa',
      platform: 'Plataforma',
      askAdvice: 'Solicitar asesoría',
      contact: 'Contacto',
      rights: '© 2026 SegurIA. Todos los derechos reservados.',
      line: 'Security Suite. Powered by N3uralia.',
    },
    home: {
      eyebrow: 'SegurIA Security Suite',
      title: 'Sabe qué está pasando. Actúa cuando importa.',
      description: 'SegurIA reúne las señales de tu operación en una vista clara, te avisa cuando algo requiere atención y deja el contexto listo para responder.',
      chips: ['Operación visible', 'Alertas claras', 'Mejor respuesta'],
      primary: 'Ver soluciones',
      secondary: 'Hablar con SegurIA',
      panelBadge: 'Operación clara',
      proof: [
        { label: 'Operación', value: 'visible' },
        { label: 'Alertas', value: 'claras' },
        { label: 'Respuesta', value: 'rápida' },
      ],
      sectionEyebrow: 'Cómo ayuda SegurIA',
      sectionTitle: 'Tres cosas simples para operar con más claridad.',
      sectionDescription: 'No necesitas perseguir sistemas ni interpretar señales aisladas. SegurIA ordena lo importante para que puedas decidir.',
      benefits: [
        {
          title: 'Ve lo que está pasando',
          description: 'Reúne el estado de tus lugares, equipos y eventos importantes en una sola lectura.',
        },
        {
          title: 'Entiende qué requiere atención',
          description: 'Recibe alertas con contexto para distinguir lo urgente del ruido cotidiano.',
        },
        {
          title: 'Actúa con información',
          description: 'Cada evento queda ordenado para responder, revisar y aprender sin perder tiempo.',
        },
      ],
      whyEyebrow: 'Una sola experiencia',
      whyTitle: 'SegurIA conecta lo que ya tienes.',
      whyDescription: 'La tecnología queda detrás. La operación queda al frente.',
      wins: [
        'Aprovecha sistemas e infraestructura compatibles ya instalados',
        'Centraliza eventos y alertas en una sola experiencia',
        'Mantiene contexto y evidencia para responder mejor',
        'Puede seguir operando localmente cuando la conectividad es limitada',
      ],
      placesEyebrow: 'Dónde se aplica',
      placesTitle: 'La misma claridad, adaptada a cada operación.',
      finalTitle: 'Menos ruido. Más claridad para actuar.',
      finalDescription: 'Cuéntanos qué necesitas proteger u operar y diseñamos una forma simple de verlo, entenderlo y responder.',
    },
    solutions: {
      heroTitle: 'Una forma más clara de operar seguridad.',
      heroDescription: 'Elige tu contexto. SegurIA adapta la misma lógica de visibilidad, alertas y respuesta a cada tipo de operación.',
      sectionTitle: 'Soluciones pensadas para el lugar donde operas.',
      sectionDescription: 'Campos, propiedades, hoteles y embarcaciones comparten una necesidad: saber qué está pasando y actuar a tiempo.',
      cta: 'Ver solución',
    },
    routes: {
      fields: {
        eyebrow: 'Campos Inteligentes',
        title: 'Sabe qué está pasando en tu campo, incluso cuando estás lejos.',
        description: 'Mantén accesos, zonas críticas y operación remota visibles, con alertas claras cuando algo requiere atención.',
        href: '/campos-inteligentes',
        image: "linear-gradient(to bottom, rgba(10, 27, 46, 0.55), rgba(10, 27, 46, 0.88)), url('https://images.unsplash.com/photo-1500595046743-cd271d694d30?q=70&w=1400&auto=format&fit=crop')",
        cards: [
          ['Operación visible', 'Accesos, caminos, bodegas y zonas críticas en una sola lectura.'],
          ['Alertas importantes', 'Entiende cuándo un evento merece atención y responde con contexto.'],
          ['Sitios remotos conectados', 'Mantén continuidad operacional aun cuando el lugar esté lejos o la conexión sea limitada.'],
        ],
      },
      properties: {
        eyebrow: 'Propiedades Inteligentes',
        title: 'Sabe qué está pasando en tu propiedad sin estar pendiente todo el día.',
        description: 'Reúne accesos, eventos y alertas importantes para cuidar tu casa, oficina o negocio con menos fricción.',
        href: '/propiedades-inteligentes',
        image: "linear-gradient(to bottom, rgba(10, 27, 46, 0.55), rgba(10, 27, 46, 0.88)), url('https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?q=70&w=1400&auto=format&fit=crop')",
        cards: [
          ['Accesos claros', 'Entiende quién entra, cuándo ocurre y qué evento necesita atención.'],
          ['Alertas sin ruido', 'Recibe información útil sin perseguir pantallas durante todo el día.'],
          ['Todo en una sola vista', 'Casa, oficina, bodega o condominio con una lectura simple de la operación.'],
        ],
      },
      hospitality: {
        eyebrow: 'Hotelería Inteligente',
        title: 'Mantén tu hotel visible y tu operación tranquila.',
        description: 'SegurIA ayuda a detectar lo importante, coordinar al equipo y responder sin afectar la experiencia del huésped.',
        href: '/hoteleria-inteligente',
        image: "linear-gradient(to bottom, rgba(10, 27, 46, 0.3), rgba(10, 27, 46, 0.9)), url('/portal/huilo-huilo.jpg')",
        cards: [
          ['Operación discreta', 'Supervisa áreas importantes sin romper la experiencia del huésped.'],
          ['Equipo coordinado', 'Alertas y contexto para que el staff sepa cuándo y dónde actuar.'],
          ['Gerencia informada', 'Cada evento relevante queda ordenado para revisar y decidir.'],
        ],
      },
    },
    detail: {
      applications: 'Lo que puedes resolver',
      capabilities: 'Capacidades clave',
      process: 'Cómo empezamos',
      processItems: [
        ['01', 'Entendemos tu operación', 'Revisamos lugares, riesgos y lo que realmente necesitas controlar.'],
        ['02', 'Conectamos lo importante', 'Integramos los sistemas compatibles que aportan información útil.'],
        ['03', 'Ordenamos las alertas', 'Definimos qué merece atención y cómo debe llegar a tu equipo.'],
        ['04', 'Mejoramos con el uso', 'Ajustamos la operación según eventos reales y prioridades.'],
      ],
      ctaTitle: 'Tu operación puede ser mucho más fácil de entender.',
      ctaText: 'Cuéntanos cómo funciona hoy y diseñamos una experiencia más clara para responder mejor.',
    },
    integrations: {
      title: 'Conectamos lo que ya tienes para que trabaje como una sola operación.',
      description: 'SegurIA puede integrarse con sistemas compatibles existentes y convertir sus señales en una experiencia simple de visibilidad, alertas y respuesta.',
      items: ['Sistemas e infraestructura existentes', 'Alertas con contexto', 'Operación centralizada', 'Evidencia y trazabilidad cuando se necesita'],
    },
    contact: {
      title: 'Cuéntanos qué necesitas controlar mejor.',
      description: 'Te ayudamos a ordenar el problema primero y la tecnología después. Partimos por tu operación, tus riesgos y tus prioridades.',
      name: 'Nombre',
      email: 'Email',
      message: 'Mensaje',
      send: 'Solicitar asesoría',
    },
  },
  en: {
    nav: {
      solutions: 'Solutions',
      portal: 'Portal',
      contact: 'Contact',
      language: 'ES',
    },
    footer: {
      description: 'SegurIA connects your operation so you can see what is happening, understand what needs attention and act better.',
      solutions: 'Solutions',
      seeSolution: 'View solution',
      clientPortal: 'Client portal',
      company: 'Company',
      platform: 'Platform',
      askAdvice: 'Request advisory',
      contact: 'Contact',
      rights: '© 2026 SegurIA. All rights reserved.',
      line: 'Security Suite. Powered by N3uralia.',
    },
    home: {
      eyebrow: 'SegurIA Security Suite',
      title: 'Know what is happening. Act when it matters.',
      description: 'SegurIA brings your operational signals into one clear view, alerts you when something needs attention and keeps the context ready for response.',
      chips: ['Visible operations', 'Clear alerts', 'Better response'],
      primary: 'View solutions',
      secondary: 'Talk to SegurIA',
      panelBadge: 'Clear operation',
      proof: [
        { label: 'Operation', value: 'visible' },
        { label: 'Alerts', value: 'clear' },
        { label: 'Response', value: 'faster' },
      ],
      sectionEyebrow: 'How SegurIA helps',
      sectionTitle: 'Three simple things for clearer operations.',
      sectionDescription: 'You should not need to chase systems or interpret isolated signals. SegurIA organizes what matters so you can decide.',
      benefits: [
        {
          title: 'See what is happening',
          description: 'Bring the state of your sites, equipment and important events into one readable view.',
        },
        {
          title: 'Understand what needs attention',
          description: 'Receive contextual alerts that separate urgent events from everyday noise.',
        },
        {
          title: 'Act with information',
          description: 'Keep each event organized so your team can respond, review and learn without wasting time.',
        },
      ],
      whyEyebrow: 'One experience',
      whyTitle: 'SegurIA connects what you already have.',
      whyDescription: 'Technology stays in the background. Operations stay in front.',
      wins: [
        'Use compatible systems and infrastructure already in place',
        'Centralize events and alerts in one experience',
        'Keep context and evidence available for better response',
        'Continue operating locally when connectivity is limited',
      ],
      placesEyebrow: 'Where it applies',
      placesTitle: 'The same clarity, adapted to each operation.',
      finalTitle: 'Less noise. More clarity to act.',
      finalDescription: 'Tell us what you need to protect or operate and we will design a simple way to see it, understand it and respond.',
    },
    solutions: {
      heroTitle: 'A clearer way to run security operations.',
      heroDescription: 'Choose your context. SegurIA adapts the same visibility, alerting and response logic to each type of operation.',
      sectionTitle: 'Solutions designed around where you operate.',
      sectionDescription: 'Fields, properties, hotels and vessels share one need: know what is happening and act on time.',
      cta: 'View solution',
    },
    routes: {
      fields: {
        eyebrow: 'Smart Fields',
        title: 'Know what is happening in your field, even when you are far away.',
        description: 'Keep access points, critical zones and remote operations visible, with clear alerts when something needs attention.',
        href: '/campos-inteligentes',
        image: "linear-gradient(to bottom, rgba(10, 27, 46, 0.55), rgba(10, 27, 46, 0.88)), url('https://images.unsplash.com/photo-1500595046743-cd271d694d30?q=70&w=1400&auto=format&fit=crop')",
        cards: [
          ['Visible operations', 'Access points, roads, storage and critical zones in one readable view.'],
          ['Important alerts', 'Know when an event needs attention and respond with context.'],
          ['Remote sites connected', 'Maintain operational continuity even when the site is distant or connectivity is limited.'],
        ],
      },
      properties: {
        eyebrow: 'Smart Properties',
        title: 'Know what is happening at your property without watching it all day.',
        description: 'Bring access, events and important alerts together to protect your home, office or business with less friction.',
        href: '/propiedades-inteligentes',
        image: "linear-gradient(to bottom, rgba(10, 27, 46, 0.55), rgba(10, 27, 46, 0.88)), url('https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?q=70&w=1400&auto=format&fit=crop')",
        cards: [
          ['Clear access', 'Understand who enters, when it happens and which event needs attention.'],
          ['Alerts without noise', 'Get useful information without chasing screens throughout the day.'],
          ['Everything in one view', 'Home, office, warehouse or community with a simple operational readout.'],
        ],
      },
      hospitality: {
        eyebrow: 'Smart Hospitality',
        title: 'Keep your hotel visible and your operation calm.',
        description: 'SegurIA helps detect what matters, coordinate the team and respond without disrupting the guest experience.',
        href: '/hoteleria-inteligente',
        image: "linear-gradient(to bottom, rgba(10, 27, 46, 0.3), rgba(10, 27, 46, 0.9)), url('/portal/huilo-huilo.jpg')",
        cards: [
          ['Discreet operations', 'Monitor important areas without disrupting the guest experience.'],
          ['Coordinated team', 'Alerts and context so staff know when and where to act.'],
          ['Informed management', 'Every relevant event stays organized for review and decisions.'],
        ],
      },
    },
    detail: {
      applications: 'What you can solve',
      capabilities: 'Key capabilities',
      process: 'How we start',
      processItems: [
        ['01', 'We understand your operation', 'We review sites, risks and what you actually need to control.'],
        ['02', 'We connect what matters', 'We integrate compatible systems that provide useful information.'],
        ['03', 'We organize alerts', 'We define what needs attention and how it should reach your team.'],
        ['04', 'We improve with use', 'We tune the operation based on real events and priorities.'],
      ],
      ctaTitle: 'Your operation can be much easier to understand.',
      ctaText: 'Tell us how it works today and we will design a clearer experience for better response.',
    },
    integrations: {
      title: 'We connect what you already have so it works as one operation.',
      description: 'SegurIA can integrate with compatible existing systems and turn their signals into a simple experience for visibility, alerts and response.',
      items: ['Existing systems and infrastructure', 'Contextual alerts', 'Centralized operations', 'Evidence and traceability when needed'],
    },
    contact: {
      title: 'Tell us what you need to control better.',
      description: 'We help organize the problem first and the technology second. We start with your operation, risks and priorities.',
      name: 'Name',
      email: 'Email',
      message: 'Message',
      send: 'Request advisory',
    },
  },
} satisfies Record<Locale, unknown>

export type MarketingCopy = (typeof marketing)[Locale]
