update public.user_operations
set role = 'viewer'
where role is null;

alter table public.user_operations
  alter column role set default 'viewer',
  alter column role set not null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'user_operations_role_check'
      and conrelid = 'public.user_operations'::regclass
  ) then
    alter table public.user_operations
      add constraint user_operations_role_check
      check (role in ('owner', 'admin', 'operator', 'technician', 'reviewer', 'viewer'));
  end if;
end $$;

create table if not exists public.wildlife_territorial_access_log (
  id bigint generated by default as identity primary key,
  operation_id uuid null references public.operations(id) on delete set null,
  actor_user_id uuid not null references auth.users(id) on delete cascade,
  action text not null,
  resource_type text not null,
  resource_id text null,
  coordinate_precision text null check (coordinate_precision is null or coordinate_precision in ('exact', 'generalized', 'hidden')),
  ip_address inet null,
  user_agent text null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists wildlife_territorial_access_operation_created_idx
  on public.wildlife_territorial_access_log(operation_id, created_at desc)
  where operation_id is not null;

create index if not exists wildlife_territorial_access_actor_created_idx
  on public.wildlife_territorial_access_log(actor_user_id, created_at desc);

alter table public.wildlife_territorial_access_log enable row level security;

drop policy if exists wildlife_territorial_access_select on public.wildlife_territorial_access_log;
create policy wildlife_territorial_access_select
  on public.wildlife_territorial_access_log
  for select
  to authenticated
  using (
    actor_user_id = (select auth.uid())
    or exists (
      select 1
      from public.user_operations access_link
      where access_link.user_id = (select auth.uid())
        and access_link.operation_id = wildlife_territorial_access_log.operation_id
        and access_link.role in ('owner', 'admin')
    )
  );

revoke all on public.wildlife_territorial_access_log from anon;
revoke insert, update, delete on public.wildlife_territorial_access_log from authenticated;
grant select on public.wildlife_territorial_access_log to authenticated;

with single_operation as (
  select user_id, max(operation_id::text)::uuid as operation_id
  from public.user_operations
  group by user_id
  having count(*) = 1
)
update public.wildlife_cameras camera
set organization_id = scope.operation_id
from single_operation scope
where camera.organization_id is null
  and camera.created_by_user_id = scope.user_id;

with single_operation as (
  select user_id, max(operation_id::text)::uuid as operation_id
  from public.user_operations
  group by user_id
  having count(*) = 1
)
update public.wildlife_inference_jobs job
set organization_id = scope.operation_id
from single_operation scope
where job.organization_id is null
  and job.submitted_by_user_id = scope.user_id;

with single_operation as (
  select user_id, max(operation_id::text)::uuid as operation_id
  from public.user_operations
  group by user_id
  having count(*) = 1
)
update public.wildlife_pilot_batches batch
set organization_id = scope.operation_id
from single_operation scope
where batch.organization_id is null
  and batch.created_by_user_id = scope.user_id;

comment on table public.wildlife_territorial_access_log is
  'Auditoria inmutable de accesos a ubicaciones y recursos territoriales de SegurIA Vision.';

comment on column public.wildlife_cameras.organization_id is
  'Identificador de operacion legado usado como alcance tenant para SegurIA Vision.';
