-- Durable application-level login throttling.
-- Only server-side service-role clients may read or write this table.

create table if not exists public.auth_login_attempts (
  id bigint generated by default as identity primary key,
  ip_hash text not null,
  email_hash text not null,
  succeeded boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists auth_login_attempts_ip_created_idx
  on public.auth_login_attempts (ip_hash, created_at desc);

create index if not exists auth_login_attempts_email_created_idx
  on public.auth_login_attempts (email_hash, created_at desc);

alter table public.auth_login_attempts enable row level security;

revoke all on table public.auth_login_attempts from anon, authenticated;
revoke all on sequence public.auth_login_attempts_id_seq from anon, authenticated;

grant select, insert, delete on table public.auth_login_attempts to service_role;
grant usage, select on sequence public.auth_login_attempts_id_seq to service_role;

comment on table public.auth_login_attempts is
  'Server-only, HMAC-anonymized login attempt records used for brute-force throttling.';
